include .env

.PHONY: lint
lint:
	golangci-lint run

.PHONY: run
run:
	OPEN_WEATHER_API_KEY=$(OPEN_WEATHER_API_KEY) TELEGRAM_TOKEN=$(TELEGRAM_TOKEN) \
	PG_HOST=$(PG_HOST) PG_PORT=$(PG_PORT) PG_PASSWORD=$(PG_PASSWORD) \
	PG_USERNAME=$(PG_USERNAME) PG_DBNAME=$(PG_DBNAME) \
	go run ./cmd/main/main.go